const ADD_MODERATOR="ADD_MODERATOR"
const DELETE_MODERATORS="DELETE_MODERATORS"
const EDIT_MODERATOR="EDIT_MODERATOR"
const UPLOAD_ARTICLE="UPLOAD_ARTICLE"
const ADMIN_FAIL_ACTION="FAIL_ADMIN_ACTION"
const ADMIN_ACTION_SUCCESS="ADMIN_ACTION_SUCCESS"
const ADMIN_LOADING="ADMIN_LOADING_ACTION"
const GET_MODERATORS="GET_MODERATORS"
export {
    ADD_MODERATOR,
    DELETE_MODERATORS,
    EDIT_MODERATOR,
    UPLOAD_ARTICLE,
    ADMIN_ACTION_SUCCESS,
    ADMIN_FAIL_ACTION,
    ADMIN_LOADING,
    GET_MODERATORS
}