const ADD_ARTICLE="ADD_ARTICLES"
const GET_ARTICLES="GET_ARTICLES"
const CONFIRM_ARTICLE="CONFIRM_ARTICLE"
const DELETE_ARTICLES="DELETE_ARTICLE"
const GET_MODERATOR_ARTICLE="GET_MODERATOR_ARTICLE"
const GET_ARTCLE_DETAILS="GET_ARTICLE_DETAILS"
const ARTICLE_ERROR="ARTICLE_ERROR"
const ARTICLE_LOADING="ARTICLE_Loading"
const EDIT_ARTICLE_BY_MODERATOR="EDIT_ARTICLE_BY_MODERATOR"
const GET_APPROVED_ARTICLES="GET_APPROVED_ARTICLES"
const ADD_ARTICLE_TO_FAVORIS="ADD_ARTICLE_TO_FAVORITES"
const GET_FAVORITS="GET_FAVORITS"
const REMOVE_FAVORITE_ARTICLE="REMOVE_FAVORITE_ARTICLE"
export {
    ADD_ARTICLE,
    GET_ARTICLES,
    CONFIRM_ARTICLE,
    DELETE_ARTICLES,
    GET_ARTCLE_DETAILS,
    GET_MODERATOR_ARTICLE,
    ARTICLE_ERROR,
    ARTICLE_LOADING,
    EDIT_ARTICLE_BY_MODERATOR,
    GET_APPROVED_ARTICLES,
    ADD_ARTICLE_TO_FAVORIS,
    GET_FAVORITS,
    REMOVE_FAVORITE_ARTICLE
}