const SEARCH_BY_TITLE="SEARCHBY_TITLE"
const SEARCH_BY_AUTHOR="SEARCH_BY_AUTHOR"
const SEARCH_LOADING="SEARCH_LOADING"
const SEARCH_ERROR="SEARCH_ERROR"
const GENERAL_SEARCH="GENERAL_SEARCH"
const FILTER_SEARCH = "FILTER_SEARCH"

export {
    SEARCH_BY_AUTHOR,
    SEARCH_BY_TITLE,
    SEARCH_LOADING,
    SEARCH_ERROR,
    GENERAL_SEARCH, 
    FILTER_SEARCH
}