const SEARCH_BY_TITLE="SEARCHBY_TITLE"
const SEARCH_BY_AUTHOR="SEARCH_BY_AUTHOR"
const SEARCH_LOADING="SEARCH_LOADING"
const SEARCH_ERROR="SEARCH_ERROR"
export {
    SEARCH_BY_AUTHOR,
    SEARCH_BY_TITLE,
    SEARCH_LOADING,
    SEARCH_ERROR
}