const SIGNUP_USER="SIGNUP_USER"
const SIGNIN_USER="SIGNIN_USER"
const USER_ERROR="USER_ERROR"
const USER_SUCCESS="USER_SUCCESS"
const USER_UPDATE_INFO="USER_UPDATE_INFO"
const RESETPASSWORD="RESET_PASSWORD"
const USER_LOADING="USER_LOADING"
const SAVE_USER_LOGIN_DATA="SAVE_USER_LOGIN_DATA"
const CONFIRM_USER_MAIL="CONFIRM_REGISTRATION"
const CLEAR_USER_INFO="CLEAR_USER_INFO"
const SAVE_ENTERED_EMAIL="SAVE_ENTERED_EMAIL"
const USER_FAIL="USER_FAIL"
const SAVE_CONFIRMATION_CODE="SAVE_CONFIRMATION_CODE"
export{
    SIGNUP_USER,
    SIGNIN_USER,
    USER_ERROR,
    USER_SUCCESS,
    USER_UPDATE_INFO,
    RESETPASSWORD,
    USER_LOADING,
    SAVE_USER_LOGIN_DATA,
    CLEAR_USER_INFO,
    CONFIRM_USER_MAIL,
    SAVE_ENTERED_EMAIL,
    USER_FAIL,
    SAVE_CONFIRMATION_CODE
}